name: Test & Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install: # fills the cache for following jobs
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup yarn
        uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

  test:
    name: Run tsc
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup yarn
        uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tsc
        run: yarn tsc --skipLibCheck


  lint:
    name: Run eslint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup yarn
        uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Linter
        run: yarn lint


